/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColorirRouteImport } from './routes/colorir'
import { Route as DesenhosRouteImport } from './routes/desenhos'
import { Route as DesenhoSlugRouteImport } from './routes/desenho.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorirRoute = ColorirRouteImport.update({
  id: '/colorir',
  path: '/colorir',
  getParentRoute: () => rootRouteImport,
} as any)
const DesenhosRoute = DesenhosRouteImport.update({
  id: '/desenhos',
  path: '/desenhos',
  getParentRoute: () => rootRouteImport,
} as any)
const DesenhoSlugRoute = DesenhoSlugRouteImport.update({
  id: '/desenho/$slug',
  path: '/desenho/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colorir': typeof ColorirRoute
  '/desenhos': typeof DesenhosRoute
  '/desenho/$slug': typeof DesenhoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colorir': typeof ColorirRoute
  '/desenhos': typeof DesenhosRoute
  '/desenho/$slug': typeof DesenhoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colorir': typeof ColorirRoute
  '/desenhos': typeof DesenhosRoute
  '/desenho/$slug': typeof DesenhoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colorir' | '/desenhos' | '/desenho/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colorir' | '/desenhos' | '/desenho/$slug'
  id: '__root__' | '/' | '/colorir' | '/desenhos' | '/desenho/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorirRoute: typeof ColorirRoute
  DesenhosRoute: typeof DesenhosRoute
  DesenhoSlugRoute: typeof DesenhoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colorir': {
      id: '/colorir'
      path: '/colorir'
      fullPath: '/colorir'
      preLoaderRoute: typeof ColorirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desenhos': {
      id: '/desenhos'
      path: '/desenhos'
      fullPath: '/desenhos'
      preLoaderRoute: typeof DesenhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desenho/$slug': {
      id: '/desenho/$slug'
      path: '/desenho/$slug'
      fullPath: '/desenho/$slug'
      preLoaderRoute: typeof DesenhoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorirRoute: ColorirRoute,
  DesenhosRoute: DesenhosRoute,
  DesenhoSlugRoute: DesenhoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
